# 실행파일 이름
TARGET = ClassBooking

# 모든 소스 파일
SRCS = ClassBooking.cpp admin.cpp classroom.cpp reservation.cpp user.cpp util.cpp models.cpp time.cpp

# 빌드
all:
	g++ -std=c++17 -Wall -o $(TARGET) $(SRCS)

# 정리
clean:
	rm -f $(TARGET)